server:
  port: 4000

  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

spring:
  datasource:
    url: jdbc:postgresql://mel.db.elephantsql.com:5432/udzptnat
    username: udzptnat
    password: Q3MJaZaIEUx6TK--V-lPlzzJiny0vAbQ
    hikari:
      maximum-pool-size: 3
      minimum-idle: 3
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

